CREATE OR REPLACE TRIGGER TRG_TARJETAS
BEFORE INSERT ON TBL_TARJETAS
FOR EACH ROW
DECLARE
    V_CANTIDAD_REGISTROS NUMBER;
    V_CODIGO_ORGANIZACION NUMBER;
    V_REGISTRO_INVALIDO EXCEPTION;
BEGIN
    SELECT C.CODIGO_ORGANIZACION
    INTO V_CODIGO_ORGANIZACION
    FROM TBL_LISTAS B
    INNER JOIN TBL_TABLERO C 
    ON (B.CODIGO_TABLERO = C.CODIGO_TABLERO)
    WHERE B.CODIGO_LISTA = :NEW.CODIGO_LISTA;
    
    SELECT COUNT(1)
    INTO V_CANTIDAD_REGISTROS
    FROM TBL_USUARIOS_X_ORGANIZACION
    WHERE CODIGO_USUARIO = :NEW.CODIGO_USUARIO
    AND CODIGO_ORGANIZACION = V_CODIGO_ORGANIZACION;

    
    IF (V_CANTIDAD_REGISTROS <= 0) THEN
        RAISE_APPLICATION_ERROR(-20000, 'ERROR');
    END IF;

END;



SELECT * FROM TBL_LISTAS;



SELECT C.CODIGO_ORGANIZACION
FROM TBL_LISTAS B
INNER JOIN TBL_TABLERO C 
ON (B.CODIGO_TABLERO = C.CODIGO_TABLERO)
WHERE B.CODIGO_LISTA = 7;



