SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TRG_TABLEROS 
BEFORE INSERT ON TBL_TABLERO
FOR EACH ROW
DECLARE
    V_CANTIDAD_REGISTROS NUMBER;
    V_CANTIDAD_TABLEROS NUMBER;
    V_REGISTRO_INVALIDO EXCEPTION;
BEGIN
    SELECT COUNT(1)
    INTO V_CANTIDAD_REGISTROS
    FROM TBL_USUARIOS_X_ORGANIZACION
    WHERE CODIGO_USUARIO = :NEW.CODIGO_USUARIO_CREA
    AND CODIGO_ORGANIZACION = :NEW.CODIGO_ORGANIZACION;
    
    SELECT COUNT(1)
    INTO V_CANTIDAD_TABLEROS
    FROM TBL_TABLERO
    WHERE NOMBRE_TABLERO = :NEW.NOMBRE_TABLERO;
    
    IF (V_CANTIDAD_REGISTROS <= 0 OR V_CANTIDAD_TABLEROS > 0) THEN
        RAISE_APPLICATION_ERROR(-20000, 'ERROR');
    END IF;

END;

begin
    INSERT INTO tbl_tablero (
        codigo_tablero,
        codigo_usuario_crea,
        nombre_tablero,
        descripcion,
        tipo_acceso,
        fecha_creacion,
        codigo_organizacion
    ) VALUES (
        52,
        203,
        'PROYECTO DE BD',
        'LOREM IPSUM DOLOR SIT AMET ',
        2,
        sysdate,
        23
    );
exception
    when others then
        rollback;
end;

SELECT * 
FROM TBL_TABLERO
WHERE CODIGO_TABLERO = 52;

SELECT COUNT(1)
FROM TBL_USUARIOS_X_ORGANIZACION
WHERE CODIGO_USUARIO = 277
AND CODIGO_ORGANIZACION = 8;

select * from TBL_USUARIOS_X_ORGANIZACION;