create or replace TRIGGER TRG_CALCULATE_SENIORITY 
BEFORE UPDATE OF ACTIVE ON EMPLOYEES 
FOR EACH ROW 
WHEN (OLD.ACTIVE = 'T' AND NEW.ACTIVE = 'F')
DECLARE
BEGIN
    :NEW.ACTIVE_TIME := SYSDATE - :NEW.HIRE_DATE;
EXCEPTION
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR=====>> ' || SQLERRM);
END TRG_CALCULATE_SENIORITY;