

DECLARE
    --ESTE ES UN COMENTARIO
    /* 
    COMENTARIO DE VARIAS LINEAS
    */
    V_NOMBRE VARCHAR2(50);
    V_APELLIDO VARCHAR2(50) := 'PEREZ';
    V_CANTIDAD_REGISTROS NUMBER;
    V_NOMBRE_CATEGORIA tbl_categorias.NOMBRE_CATEGORIA%TYPE;
    V_CODIGO_CATEGORIA tbl_categorias.CODIGO_CATEGORIA%TYPE;
    
    type PRODUCTO IS RECORD (
        CODIGO_PRODUCTO NUMBER,
        NOMBRE VARCHAR2(500),
        PRECIO NUMBER
    );
    
    V_PRODUCTO PRODUCTO;
    V_PRIMER_PRODUCTO PRODUCTO;
    V_OTRO_PRODUCTO TBL_PRODUCTOS%ROWTYPE;
BEGIN
    V_PRODUCTO.CODIGO_PRODUCTO := 666;
    V_PRODUCTO.NOMBRE := 'SHAMPOO';
    V_PRODUCTO.PRECIO := 10000;
    
    
    SELECT COUNT(1) 
    INTO V_CANTIDAD_REGISTROS
    FROM tbl_categorias;
    
    SELECT nombre_categoria, CODIGO_CATEGORIA
    INTO V_NOMBRE_CATEGORIA, V_CODIGO_CATEGORIA
    FROM tbl_categorias
    WHERE CODIGO_CATEGORIA = 1;
    
    SELECT *
    INTO V_PRIMER_PRODUCTO
    FROM TBL_PRODUCTOS
    WHERE ROWNUM = 1;
    
    SELECT *
    INTO V_OTRO_PRODUCTO
    FROM TBL_PRODUCTOS
    WHERE ROWNUM = 1;
    
    V_NOMBRE := 'JUAN';
    DBMS_OUTPUT.PUT_LINE('HOLA ' || V_NOMBRE || ' ' || V_APELLIDO);
    DBMS_OUTPUT.PUT_LINE('CANTIDAD DE REGISTROS: ' || V_CANTIDAD_REGISTROS);
    DBMS_OUTPUT.PUT_LINE('CATEGORIA: ' || v_nombre_categoria);
    DBMS_OUTPUT.PUT_LINE('CODIGO CATEGORIA: ' || v_CODIGO_categoria);
    DBMS_OUTPUT.PUT_LINE('PRODUCTO: ' || V_PRODUCTO.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('PRIMER PRODUCTO: ' || V_PRIMER_PRODUCTO.NOMBRE);
    DBMS_OUTPUT.PUT_LINE('OTRO PRODUCTO: ' || V_OTRO_PRODUCTO.NOMBRE);
END;




select  tbl_productos.*, rowid, ROWNUM 
from tbl_productos
ORDER BY 2;






SELECT A.*, ROWNUM

    FROM TBL_PRODUCTOS A
    WHERE ROWNUM = 3;
    
    COMMIT;


