--Bloques Anonimos
--Procedimientos Almacenados
--Funciones
--Paquetes


CREATE OR REPLACE FUNCTION F_SUMAR(A NUMBER, B NUMBER) 
RETURN NUMBER IS 
BEGIN
    RETURN A + B;
END F_SUMAR;


BEGIN
    DBMS_OUTPUT.PUT_LINE('RESULTADO: ' || F_SUMAR(5, 6));
END;

SELECT F_SUMAR(5, 6) 
FROM DUAL;


---CREAR FUNCION QUE RETORNE EL SALARIO TOTAL DE UN DEPARTAMENTO QUE SE ENVIE DE PARAMETRO


CREATE OR REPLACE FUNCTION F_SALARIO_DEPARTAMENTO (P_DEPARTMENT_ID NUMBER)
RETURN NUMBER IS
    V_SALARIO_TOTAL NUMBER;
BEGIN
    SELECT SUM(SALARY)
    INTO V_SALARIO_TOTAL
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = P_DEPARTMENT_ID;
    
    RETURN V_SALARIO_TOTAL;
END;


SELECT F_SALARIO_DEPARTAMENTO(20)
FROM DUAL;


SELECT (6000/19000) * 100 --31.57%
FROM DUAL;

SELECT (13000/19000) * 100 --68.42.57%
FROM DUAL;

SELECT  FIRST_NAME, 
        LAST_NAME, 
        ROUND((SALARY/F_SALARIO_DEPARTAMENTO(DEPARTMENT_ID)) * 100, 2) AS PORCENTAJE 
FROM EMPLOYEES;

SELECT  UPPER(FIRST_NAME), 
        LOWER(LAST_NAME), 
        TRUNC((SALARY/F_SALARIO_DEPARTAMENTO(DEPARTMENT_ID)) * 100) AS PORCENTAJE 
FROM EMPLOYEES;




